#!/usr/bin/env sh

# install helm
helm init --history-max 200

# wait for tiller
sleep 30

# install NGINX
helm install stable/nginx-ingress

# install dashboard
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta4/aio/deploy/recommended.yaml

# configure dashboard user
kubectl apply -f ./config/dashboard-adminuser.yaml

# get user token
kubectl -n kubernetes-dashboard describe secret $(kubectl -n kubernetes-dashboard get secret | grep admin-user | awk '{print $1}')

